#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get update
sudo apt-get install -y nginx 
echo "Hello World!" > index.html
sudo mv index.html /var/www/html


echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/AyBims permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sudo service nginx restart
