#!/usr/bin/env bash
# Install load balancer in lb-01

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 266743-web-01 34.203.77.75:80 check
    server 266743-web-02 18.204.8.189:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
